### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by yakir12** [rofinn/FilePathsBase.jl#103]
This is a feature request, not even that, it's more of a discussion about a possible enhancement.

In a similar way to how `/` joins paths, it would be cool to have some special operator for adding an extension to a path/string. Just a thought.

**Comment by rofinn** [comment]
Wouldn't that at best save you a single character though? 
```julia
julia> using FilePathsBase

julia> using FilePathsBase: /

julia> p"foo" / "bar" / "baz" * ".txt"
p"foo/bar/baz.txt"
```
vs 
```julia
julia> p"foo" / "bar" / "baz" . "txt"
p"foo/bar/baz.txt"
```
Do extensions work differently on different filesystems (like path separators) cause I thought they were just a convention?

**Comment by yakir12** [comment]
Nah, you're totally right. Closing this now :)
