### ISSUE TITLE
`mkpath` isn't the same as `mkdir(...; recursive=true)`

### ISSUE THREAD

**Issue by ericphanson** [rofinn/FilePathsBase.jl#109]
because they have different behavior when the directory already exists. In Base Julia, `mkpath` does not error if the path already exists, but `mkdir` does.

Due to

https://github.com/rofinn/FilePathsBase.jl/blob/5e7da1f9ff504733ca56a838081337187277cd17/src/aliases.jl#L17

S3Paths have the issue that calling `mkpath` twice on the same path errors:
e.g.
```julia
using AWSS3
path = S3Path(...)
mkpath(path)
mkpath(path) # errors
```
vs
```julia
path = "test"
mkpath(test)
mkpath(test)
```

This inconsistency adds difficulties for writing generic code that has abstracted over the path, e.g. [Onda's Paths API](https://beacon-biosignals.github.io/Onda.jl/dev/#Paths-API-1) assumes it can call `mkpath` on the same path more than once.

**Comment by ericphanson** [comment]
Oh, looks like this was fixed on master already by https://github.com/rofinn/FilePathsBase.jl/pull/104. Thanks @kolia!

@rofinn can we please get a release with the fix?

**Comment by rofinn** [comment]
https://github.com/JuliaRegistries/General/pull/27914

**Comment by ericphanson** [comment]
thanks very much!
