### ISSUE TITLE
`joinpath` strips out path information when a parameter contains leading slash

### ISSUE THREAD

**Issue by omus** [rofinn/FilePathsBase.jl#124]
```julia
julia> joinpath("s3://", "a", "b")
"s3://a/b"

julia> joinpath("s3://", "a", "/b")
"/b"
```

**Comment by omus** [comment]
Whoops, I didn't realize this was a `Base.Filesystem` behaviour

**Comment by rofinn** [comment]
I actually think we might still want to drop this behaviour since it's unintuitive (IMHO) and introduces some weird type instabilities that make it even harder to reason about what `joinpath` is doing.
