### ISSUE TITLE
`mktempdir` missing trailing `/`

### ISSUE THREAD

**Issue by ericphanson** [rofinn/FilePathsBase.jl#127]
Not sure if this should get fixed here or in AWSS3: https://github.com/JuliaCloud/AWSS3.jl/issues/206

**Comment by ericphanson** [comment]
I think this is related to my question here: https://github.com/rofinn/FilePathsBase.jl/issues/128#issuecomment-922099259. I.e. should methods for AbstractPaths always do the trailing `/`, or should that be only in AWSS3's methods.

**Comment by rofinn** [comment]
I think that should be up to the filesystem specific implementation to decide. AFAIK, all unix, linux, macos and windows filesystem don't care, so that seems rather restrictive.

**Comment by ericphanson** [comment]
I agree most filesystems don't care, but I think the usual API principle is to accept as much as possible, and emit as conservatively as possible, in order to be as composable as possible. So I think it would be restrictive to *require* `/`s from users (which would be accepting less) but not restrictive to *emit* them when possible (which would be having more conservative outputs that are more likely to be accepted downstream).

**Comment by rofinn** [comment]
Agreed. I think adding that specific case to AWSS3 probably makes more sense.
