### ISSUE TITLE
Errors with recursive `cp` with S3Paths

### ISSUE THREAD

**Issue by ericphanson** [rofinn/FilePathsBase.jl#128]
If `src` has nested directories and the `dst` is an `S3Path`, we get errors since we are missing final `/`s when we `readdir` a local directory and get the names.

I think either:
* `readdir(::AbstractPath)` should add in `/`s to directories when reading local paths (AWSS3 already does this for remote paths), or
* We should modify `cp` to insert `/`s as needed

An somewhat messy example of the 2nd case:
```julia
function Base.cp(src::AbstractPath, dst::AbstractPath; force=false, follow_symlinks=false)
    if exists(dst)
        if force
            rm(dst; force=force, recursive=true)
        else
            throw(ArgumentError("Destination already exists: $dst"))
        end
    end

    if !exists(src)
        throw(ArgumentError("Source path does not exist: $src"))
    elseif isdir(src)
        mkdir(dst)

        for fp in readdir(src)
            src_fp = src / fp
            dst_fp = dst / fp
            if isdir(src_fp) && !endswith(dst_fp, "/")
                dst_fp *= "/"
            end
            cp(src_fp, dst_fp; force=force)
        end
    elseif isfile(src)
        write(dst, read(src))
    elseif islink(src)
        follow_symlinks ? symlink(readlink(src), dst) : write(dst, read(FilePathsBase.canonicalize(src)))
    else
        throw(ArgumentError("Source path is not a file or directory: $src"))
    end

    return dst
end

```

**Comment by ericphanson** [comment]
@rofinn do you have a preference here for changing `readdir(::AbstractPath)` to add trailing `/`s for directories, or to modify `cp` to add them when doing the recursive copy? Or do modify `cp` to add them only when one argument is a S3Path (in AWSS3)?

**Comment by rofinn** [comment]
Hmm, I don't think this should be changed in FilePathsBase at all. The trailing `/` requirement is specific to AWSS3, so yeah, a `cp` method should be added for specifically dealing with `S3Path`s.

**Comment by ericphanson** [comment]
Ok, can fix it there. This seems like a recipe for ambiguities though, if many path types need to define their own `cp`, since we need to define it when one of the arguments if a `S3Path`, and the other is any `AbstractPath`, so if another path type needs to do that it will clash.

I think the fallback method should be as generic as possible (re- https://github.com/rofinn/FilePathsBase.jl/issues/127#issuecomment-922110737), and if handling `/`s in a generic way is outside the scope of FilePathsBase, then `AWSS3.S3Path` should not subtype AbstractPath, since it doesn't fit the API.

**Comment by rofinn** [comment]
One thing that's come up is that the `Base.Filesystem` API itself is inconsistent about how it handles `/` internally. For example, `isdirpath` is a largely useless function as it stands. If we came up with a consistent default API for handling trailing separators in a lossless way then I think that would go a long way. The big issue for FilePathsBase.jl is that it's trying to maintain a consistent API with Base.Filesystem, so that things like `basename`, `joinpath`, `cp`, etc work regardless of what type you pass in.
