### ISSUE TITLE
Define `startswith` and `endswith`?

### ISSUE THREAD

**Issue by ericphanson** [rofinn/FilePathsBase.jl#132]
This comes up in https://github.com/rofinn/FilePathsBase.jl/issues/129#issuecomment-915121198 for example.

**Comment by rofinn** [comment]
I'm reluctant to add any string API methods to paths because they're fundamentally different concepts. IMHO, `startwith` and `endswith` would just be `first(fp.segments)` and `last(fp.segments)`. If you want to do your own string manipulation then you should call `string(fp)`.

**Comment by ericphanson** [comment]
How would you check if a generic AbstractPath ends with a `/`? e.g. to do https://github.com/rofinn/FilePathsBase.jl/issues/128#issue-990301133

**Comment by rofinn** [comment]
Sounds like something path specific. In general, the expectation is that you convert the path to a string if you want to perform string operations on it.
