### ISSUE TITLE
`eof(::FileBuffer)` incorrectly returns `true` before filling the buffer

### ISSUE THREAD

**Issue by iamed2** [rofinn/FilePathsBase.jl#134]
According to the `eof` docs:

> If the stream is not yet exhausted, this function will block to wait for more data if necessary, and then return `false`.

The current behaviour of always returning `true` before the first read means that the `write(A::IO, B::IO)` method (for `B<:FileBuffer`) and similar patterns are currently broken. 

This is currently causing a problem for [CSV.jl](https://github.com/JuliaData/CSV.jl/pull/892#issuecomment-917037294) with `S3Path` and is also causing https://github.com/rofinn/FilePathsBase.jl/issues/126.

**Comment by nickrobinson251** [comment]
Do you know how you'd like to see this fixed?

Do we want to read the file into the buffer before that check, e.g.
```diff
-Base.eof(buffer::FileBuffer) = eof(buffer.io)
+function Base.eof(buffer::FileBuffer)
+    if position(buffer) == 0
+        _read(buffer)
+        seekstart(buffer)
+    end
+    return eof(buffer.io)
+end
```
or do we want to avoid reading the file into the buffer and check the file directly like
```julia
-Base.eof(buffer::FileBuffer) = eof(buffer.io)
+function Base.eof(buffer::FileBuffer)
+    if position(buffer) == 0
+        return size(buffer.path) == 0
+    end
+    return eof(buffer.io)
+end
```
?

**Comment by iamed2** [comment]
The former; the docs say following what I quoted above: 
> Therefore it is always safe to read one byte after seeing `eof` return `false`.
