### ISSUE TITLE
function for total directory size

### ISSUE THREAD

**Issue by ExpandingMan** [rofinn/FilePathsBase.jl#136]
See the discussion [here](https://github.com/JuliaCloud/AWSS3.jl/pull/211#).  On most filesystems, `filesize` and `stat.size` do not return the integrated size of all directory contents.  As far as I know there is no standard function for this in the interface yet.

An advantage of having a separate function for this is that many filesystems have to iterate the leaves of a tree to determine this, which tends to be a much more expensive operation than most of the basic file system stuff.

**Comment by rofinn** [comment]
I'm not sure what you're asking here... How would making this a separate function be any less expensive than just `mapreduce(filesize, sum, walkpath(p"my/directory/path"))`? I guess we could include a human readable flag for the result, but that already seems like a pretty convenient one liner already and this has the flexibility of an arbitrary iterable of paths to consider, so it'd play nice with the Glob support in FilePaths.jl.

**Comment by ExpandingMan** [comment]
Unfortunately that does not work in the AWSS3.jl case because it generates an excessive number of HTTP calls.  The issue is that, even though `walkpath` involves a single (well, it's actually paginated, so it can be many, but let's call it one) call, this only returns the paths which do not contain metadata, so new calls must be made to obtain all the file sizes.  Additionally, on local filesystems this arguably does not work because `filesize(dir)` is non-zero, though I suppose it can be argued that it's supposed to return the value that it does rather than ignoring the directories themselves (it's a tiny difference anyway).

I suppose we could get around the need for this with a version of `walkpath` that returns all metadata rather than a dedicated function for total directory size, but, at least in AWSS3.jl, there may be some concurrency concerns around this (and for the same reasons I don't think keeping the metadata permanently in the `S3Path` object is an option).

**Comment by rofinn** [comment]
I see, so the performance impact is really just a special case for `S3Path`s. I suppose FilePathsBase.jl could implement two default methods that AWSS3 could overload:

```julia
diskusage(fp::AbstractPath) = diskusage(walkpath(fp))
diskusage(itr) = mapreduce(filesize, sum, itr)
```

For `S3Path` you could always overload the first method I guess?

**Comment by ExpandingMan** [comment]
You're right that right now it's a special case of `S3Path` but I would like to emphasize that this is potentially problematic for *any* remote source.

Your original comment got me to re-think this a bit, I had considered that perhaps it would be better to have a version of `walkpath` that returns `Stat` structs instead of just the path, but I thought about it a bit more, and this would always leave open the possibilty that it is inefficient for remote sources (e.g. it would work fine for `S3Path` but it would be inefficient if S3 added a call that does it on the server side).

So I think this `diskusage` is probably our best bet (also a better name than my `dirsize` because it makes sense for both directories and files), and yes, that definitely works for `S3Path`.

**Comment by rofinn** [comment]
Also, it's analogous to `du` which I think is what you're looking for right?

**Comment by ExpandingMan** [comment]
Yes, good name.

**Comment by rofinn** [comment]
Closing, as #137 has been merged and tagged https://github.com/JuliaRegistries/General/pull/45104
