### ISSUE TITLE
`mktempdir` should ensure no collisions

### ISSUE THREAD

**Issue by ericphanson** [rofinn/FilePathsBase.jl#142]
`uuid4()` isn't good enough because inside a `@testset` the global RNG will be reset, so you can make the directory more than once. I've been using
```julia
function Base.mktempdir(parent::S3Path)
    already_exists = true
    local fp
    # ensure we get a new one. How can we not? If someone (`@testset`, cough cough)
    # messes with the global RNG.
    while already_exists
        fp = joinpath(parent, string(uuid4(), "/"))
        already_exists = exists(fp)
    end
    mkpath(fp)
    return fp
end
```

**Comment by iamed2** [comment]
Has this been observed? UUIDs docs say it does not use the `GLOBAL_RNG` https://github.com/JuliaLang/julia/blob/master/stdlib/UUIDs/src/UUIDs.jl#L91

**Comment by ericphanson** [comment]
No, I can't reproduce it. I guess I must have had some other issue and been mistaken about the cause.

**Comment by rofinn** [comment]
Okay, I'll close the open PR and this issue.
