### ISSUE TITLE
Simplify dependencies

### ISSUE THREAD

**Issue by rafaqz** [rofinn/FilePathsBase.jl#171]
I have been asked if it makes sense to add this as a dependency in much of the geospatial data ecosystem. 

I think it does, but it seems that this package has a few too many dependencies to be a low-level dependency of other packages? Now that these base standard libs are not in the system image these package have real costs.

It seems to me that:
- MMap.jl is can be in an extension (its just one method?)
- UUIDs.jl is it really needed? `Base.tempname` doesn't use it.
- Printf.jl seems to be needed for one call to `@sprintf` - can we just use `sprint` ?
- Test.jl can be in an extension

CC @asinghvi17

**Comment by rofinn** [comment]
Interesting, I haven't been paying close attention to Julia lately and didn't realize they were removed from the sysimg. I'm not sure I agree with the decision, but if it's easier to define extensions now then I'm fine split up that functionality. My understanding is that Requires.jl isn't needed anymore? When I used that for FilePaths.jl it came with significant overhead.

**Comment by rafaqz** [comment]
Yes, extensions are very easy and built in now, with none of the Requires.jl downsides. Especially including Test as a dependency is something I've seen complaints about recently, and everyone is switching to putting it in an extension.

**Comment by rofinn** [comment]
I think this is good to close now. If we should try to isolate dates as well, feel free to open a separate issue.
