### ISSUE TITLE
Circular dependency warning

### ISSUE THREAD

**Issue by ufechner7** [rofinn/FilePathsBase.jl#179]
Running the following code using Julia 1.10.5 on Linux:
```
#!/bin/bash -eu
rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
git clone https://github.com/ufechner7/KiteModels.jl.git
cd KiteModels.jl/bin
./create_sys_image --update
```
results in:
```
┌ Warning: Circular dependency detected. Precompilation will be skipped for:
│   CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
│   FilePathsBaseTestExt [36f6b4e4-024d-52bd-a01f-148eb20c09de]
│   FilePathsBaseMmapExt [968c5e7e-8fc3-5f0f-93d2-8a5e0e125e4f]
└ @ Pkg.API ~/.julia/juliaup/julia-1.10.5+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:1279
```
The reason might be that CSV.jl depends on `FilePathBase` and `Mmap`, and `FilePathsBaseMmapExt` also depends on `Mmap`.

Can this be fixed?

**Comment by rofinn** [comment]
Hmm, I might need to ask the Pkg team about that. A few things to note.

1. That should just makes `Mmap` a shared dependency. A circular dependency would be if CSV.jl and FilePathsBase.jl directly (or indirectly) depended on each other.
2. In a regular environment, I can precompile both CSV and FilePathsBase without any issue, so maybe this has something to do with creating a system image?

```
FilePathsBaseExt » julia --project=.                                                                                                                                                                                   ~/r/t/FilePathsBaseExt
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.5 (2024-08-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using FilePathsBase, CSV
Precompiling FilePathsBase
  4 dependencies successfully precompiled in 2 seconds
Precompiling CSV
  18 dependencies successfully precompiled in 13 seconds. 5 already precompiled.
```

FWIW, I also tried running your script in an isolated VM and it errors because "`OrdinaryDiffEqBDF` is a direct dependency, but does not appear in the manifest."

**Comment by ufechner7** [comment]
> 2\. In a regular environment, I can precompile both CSV and FilePathsBase without any issue, so maybe this has something to do with creating a system image?

This issue was indeed connected to the fact that I precompiled the system image with the parameter "include_transitive_dependencies=false". Changing that to " include_transitive_dependencies=true" made the warning go away.

**Comment by ufechner7** [comment]
Feel free to close this issue.
