### ISSUE TITLE
Log a warning if file exists and overwrite is not set?

### ISSUE THREAD

**Issue by oxinabox** [rofinn/FilePathsBase.jl#18]
The behavour of not overwriting files by default caught me off-guard.

`Base.download(::AbstractString, ::AbstractString)`  always overwrites.

I assumed this would be the same.

Not overwriting by default is a valid choice,
but it would be useful to log something about it.

**Comment by rofinn** [comment]
I've just changed the behaviour to better align with base. https://github.com/rofinn/FilePathsBase.jl/blob/master/src/path.jl#L528
