### ISSUE TITLE
Minimum set of path operations

### ISSUE THREAD

**Issue by rofinn** [rofinn/FilePathsBase.jl#24]
Minimum Required:

- `constructors`
- `ispathtype`
- `parts`
- `root`
- `read`
- `write`
- `readdir`
- `chown`/`chmod`?

Derived Defaults:
- `open` defaults to reading and writing an `IOBuffer` (maybe define a `FileBuffer` that should be flushed/closed to write)?
- `copy` and `move` using `read` + `write` (permissions?)
- `download` using `copy` with different path types
- `walk` and `glob` using `readdir`
- `sync` using `walk` and `copy` (is last modified a consistent assumption?)
- abstract path manipulations (e.g., `basename`, `extension`, `norm`, `rel`, `real`, `abs`) with some assumptions?
- `tmp` related functions based on `root`
- `mkdir` default to a no-op?

**Comment by oxinabox** [comment]
Maybe should have some semi-traits,
`isreadable`, `iswriteable`

**Comment by oxinabox** [comment]
`isabs` is needed for `relative`,
can it be derived?
I feel like some paths can only be absolue, like `S3Paths`,

**Comment by rofinn** [comment]
I believe the only one of those path operations that is path type specific is `realpath` because it also handles symbolic links. I think `abs`, `norm` and `relative` can all be derived using just the `.` and `..` convention.

**Comment by rofinn** [comment]
Alright, I think I'm mostly happy with the existing defaults now. I'm sure there will be a few things that I've missed, but that'll just come up by defining new path types. The only thing that I still need to implement is a generic sync method.
