### ISSUE TITLE
 Handle Paths that need configurations

### ISSUE THREAD

**Issue by oxinabox** [rofinn/FilePathsBase.jl#29]
Some file types might need to pass around extra keyword arguments,
to all operations.

For example an `S3Path` might need to pass around some creditials in a `config` kwarg.

it would be nice if `PosixPath` and `WindowsPath` operations would accept this extra kwarg,
and just ignore it.

That way I can write code that works for both the same way,
e.g. a symetrical `sync`  operation that doesn't know if it is syncing up or down,
but is just implemented on top of `isfile(path; config=myconfig)` and `copy(src, dest; config=myconfig)` etc

**Comment by omus** [comment]
Seems odd to me to pass around a keyword to functions and expect it to be ignored sometimes. Also, what should happen if a new path takes a config and you pass in an incompatible type?

What if instead we did something like make `S3Path` contain an optional reference to a config and then if you need to change the config you do `S3Path(s3_path, config=myconfig)` then you don't have to make all of these functions take keywords which they may ignore.

**Comment by oxinabox** [comment]
I think this works, and @rofinn  and I have discussed it before.
I want to sit down and think it through a bit more,
consider how it would interact with equality,
and perhaps if there are cases where one might want to access same file with different credentials, and if that has an impact.
Compare and contrast with https://github.com/rofinn/FilePaths.jl/issues/36

And more broadly think about how it would interact with FTPPaths,
and Open Stack SwiftPaths.

**Comment by oxinabox** [comment]
Some scattered thoughts:

I like the API that you can have a path that is unconfigured:
`path=S3Path("MyBucket/myfile")`
then call `configured_path = configure(path, myconfig)`
And presumably clear that config later.

It feels a bit odd if an unconfigured path uses a default config though.
But I don't see a way around that, and I guess it makes sense.
Not sure why it feels odd.

So when it comes to Open Stack Swift.
This is basically self-hosted S3.
Conceptually, Open Stack Swift  treats the Server as path of the configuration,
not as part of the path.
But the same path  on different servers is absolutely a differnet thing.
So should not have equality there.
(And perhaps in general the server should be actually treated as part of the path and they think about it wrong).

I think this idea works.

**Comment by rofinn** [comment]
Yeah, I think I largely agree with that. It also should be easy to add in as needed rather than requiring some general API for it right now.

**Comment by rofinn** [comment]
Gonna close this for now. If we decide that we want to make `configure` part of the API later we can, but for now, it doesn't even seem necessary for the S3Path type.
