### ISSUE TITLE
Should we really add a method to `norm`?

### ISSUE THREAD

**Issue by davidanthoff** [rofinn/FilePathsBase.jl#3]
Now that this function is in ``LinearAlgebra``, it seems weird...

**Comment by rofinn** [comment]
Could rename it to `normalize` I guess. I really wish dynamic method merging was a thing that julia supported.

**Comment by rofinn** [comment]
Alright, I think if the general community is opposed to reusing base names then I think we should pull the trigger on this pre-1.0.

Proposed Renames:

- `norm` -> `normalize` (keeping `normpath`as an undeprecated alias)
- `abs` -> `absolute` (keeping `abspath` as an undeprecated alias)
- `real` -> `resolve` (keeping `realpath` as an undeprecated alias)

I'm less sure about changing these:
- `size`
- `/`

Proposed Removals:

- `move`
- `remove`

Proposed Aliases:

- `modified` -> `mtime`
- `created` -> `ctime`

**Comment by davidanthoff** [comment]
I think I'm more opposed to using names from stdlibs than from base, but I'm also not really sure, to be honest :)

**Comment by iamed2** [comment]
I support all the proposals, except I think `resolve` should be `canonicalize`, as in http://man7.org/linux/man-pages/man3/canonicalize_file_name.3.html

I'm not sure if `modified` and `created` are specific enough but I'm leaning in their favour.

I will also say that `normalize` also exists, with a method on `AbstractVector`, but it doesn't have a generic method so there would be no conflict in that case.

**Comment by rofinn** [comment]
> `resolve` also means `absolute` in Python's pathlib.

That's not entirely true. `absolute` is a separate undocumented method which does a different thing. I actually like that version of `absolute` because each method does a version specific thing.

- `normalize` -> resolve `.` and `..` type references (doesn't require path to exist)
- `absolute` -> include `cwd` to make a relative path absolute (doesn't require path to exist and doesn't try to resolve symlinks or `.` and `..` references.
- `resolve` -> normalize |> absolute |> follows symlinks and requires path to exist. (not sure I agree with the `normalizing` and `absolute` parts of this, but as a top level function I guess it works).

https://github.com/python/cpython/blob/master/Lib/pathlib.py#L1160

**Comment by iamed2** [comment]
Sorry, I got mixed up because `resolve` does what `abspath` does, but I didn't see that `abspath` does normalization and `absolute` does not.

**Comment by rofinn** [comment]
Okay, my updated proposal is:

- `normalize` -> same as above
- `absolute` -> same as above
- `resolve` -> resolve symlinks
- `canonicalize` -> `normalize |> absolute |> resolve`

This means that folks can mix and match which operations they want individually and if we're concerned about name collisions I think it would be fine to only export `canonicalize` if necessary.

**Comment by davidanthoff** [comment]
I assume we are going with US spelling with `z` and not the `s`s in the last post?

**Comment by rofinn** [comment]
No, that's intentional to avoid further conflicts with `LinearAlgebra`. I've grown rather tired of not having dynamic method merging in Julia.

**Comment by davidanthoff** [comment]
I don't think we should try to solve this by using regional different spellings, that seems a really weird way to me around this problem... I also think that would significantly decrease the likelihood that this package at some point will make it into the stdlib.

**Comment by rofinn** [comment]
> I don't think we should try to solve this by using regional different spellings, that seems a really weird way to me around this problem...

Well I think the general direction of the community regarding method merging isn't a great solution either. This is why we just have functions like `joinpath`, `normpath`, etc in base and most people who describe liking the idea of this package bring up that `joinpath` seems broken if you know that you're passing a path type.

> I also think that would significantly decrease the likelihood that this package at some point will make it into the stdlib.

At this point, I don't really see this package being part of the stdlib anytime soon anyways.

**Comment by davidanthoff** [comment]
Maybe we should just be using `normpath`? That doesn't conflict with anything and folks are used to it?

I also wonder whether we should try to involve the core team in these decisions more. I really _do_ hope that this might make it into the stdlib at some point, and many of the decisions here don't really have a clear "best" answer, so it might be most useful to make decisions that are most amendable to the core team.

**Comment by rofinn** [comment]
> Maybe we should just be using normpath? That doesn't conflict with anything and folks are used to it?

Yes, that's already a supported alias for interop with strings. My gripe with that is it seems rather redundant to say `normpath` or `joinpath` when you're clearly passing in a path. General verbs should be able to used within the context of the nouns that they operate over.

> I also wonder whether we should try to involve the core team in these decisions more. I really do hope that this might make it into the stdlib at some point, and many of the decisions here don't really have a clear "best" answer, so it might be most useful to make decisions that are most amendable to the core team.

That's largely why I've been making the changes I have (e.g., #53, #58). My feeling is that the core team doesn't really have the time and I'm not entirely clear what the advantage of having a stdlib would be... I'd like to think it would mean more eyes, but many people have told me that stdlibs are where code goes to die.

**Comment by davidanthoff** [comment]
Yeah, good points... Maybe we just should push the package as is more so that more folks start to use it...

**Comment by rofinn** [comment]
Yeah, I can probably also work a bit more on slight ecosystem improvements (e.g., support for FileIO.jl, Glob.jl, URIParser.jl) and better documentation (e.g., decision choices, `FilePaths.@compat`, writing generic filepaths code).
