### ISSUE TITLE
Should `mktmp` extend `Base.mktemp`?

### ISSUE THREAD

**Issue by nickrobinson251** [rofinn/FilePathsBase.jl#40]
Same for `mktmpdir` / `mktempdir`

As far as I can tell it has the same API/methods.

**Comment by rofinn** [comment]
The reason we don't is because we also want to support a no-arg version that returns a system path type.

**Comment by rofinn** [comment]
@nickrobinson251 Is this good to close or do you have an alternate proposal for the no-arg condition?

**Comment by nickrobinson251** [comment]
I see. You're of course right that we can't change the behaviour of no-arg `mktemp`, an alternative awkward workaround would be to just have to specify that you want a `Path` returned e.g. something like `Base.mktemp(::Type{<:SystemPath}) = mktemp(Path(tempdir()))` or `mktemp(P::Type{Union{PosixPath, WindowsPath}}) = mktmp(P(tempdir()))`

So `mktmp()` becomes `mktemp(PosixPath)`. It's a lot of effort just to use the `mktemp` name... I certainly understand if you think just changing the function name to `mktmp` is the better workaround!

**Comment by rofinn** [comment]
Hmmm, I suppose passing in the type wouldn't be unreasonable and it'd also be more explicit.
