### ISSUE TITLE
Support `splitext`

### ISSUE THREAD

**Issue by nickrobinson251** [rofinn/FilePathsBase.jl#41]
Using a Path with DataDeps.jl I hit
```
ERROR: MethodError: no method matching splitext(::PosixPath)
Closest candidates are:
  splitext(::String) at path.jl:195
  splitext(::AbstractString) at path.jl:481
```

Is there any reason not to have `Base.splitext(p::AbstractPath) = filename(p), extension(p)`?

**Comment by rofinn** [comment]
It's unclear what the behaviour of `splitext` for filepaths should be (e.g., `(filename(p), extension(p))` does not match the base behaviour).

```
julia> splitext("foo/bar.tar.gz")
("foo/bar.tar", ".gz")

julia> filename(p"foo/bar.tar.gz")
"bar"

julia> extension(p"foo/bar.tar.gz")
"gz"
```

**Comment by rofinn** [comment]
@nickrobinson251 Do you have a strong opinion on what should be returned? Should it just return the same string output as `splitext`?

**Comment by nickrobinson251** [comment]
Interesting questions! Some rambling thoughts:

- I have no strong opinion - and thanks for the example; I've come agree that it is unclear what the behaviour of `splitext` for filepaths should be.

- My main motivation for opening this was to help with compatibility with packages that have written path-handling code using Base's paths-are-string functions, in which case I naively expected:

```julia
splitext("foo/bar.tar.gz")
("foo/bar.tar", ".gz")

splitext(p"foo/bar.tar.gz")
(p"foo/bar.tar", ".gz")  # or ("foo/bar.tar", ".gz")  
```

- I thought `filename(p), extension(p)` would give this but I had only tested it on a bad case (so ignore that suggestion). 

- As I say, i hadn't really thought about it in detail... I just expected that given`a, b = splitext(p)`, then  `p == a * b`

- Given we have `extension` and `extensions` (which I think is very nice) - if we agreed on the above behaviour - we could potentially have
```
splitext(p"foo/bar.tar.gz")
(p"foo/bar.tar", ".gz")

splitexts(p"foo/bar.tar.gz")
(p"foo/bar.tar", (".tar", ".gz"))
```
But this is getting ahead of things.

- Also the more I look at it, the more I dislike that `splitext` returns `".gz"` and not just `"gz"` (even though this breaks the `p == a * b` thing)

Complicated, these filepaths...

- I like that FilePaths gives us the opportunity to do things better. Perhaps I am just not sure how to navigate the transition from "paths are Strings" to "paths are Paths"

**Comment by rofinn** [comment]
Okay, since the most common use case for `splitext` is to do string concatenation of the first argument with some other extension I think it's fine to return a path as the first argument. `p"foo/bar" * ".zip"` would work as expected even with path types.

> Perhaps I am just not sure how to navigate the transition from "paths are Strings" to "paths are Paths"

This is an ongoing challenge
