### ISSUE TITLE
`download` should copy into directories?

### ISSUE THREAD

**Issue by rofinn** [rofinn/FilePathsBase.jl#48]
This would differ from Base.download so we should probably try updating julia first? This was triggered from a conversation in https://github.com/oxinabox/DataDeps.jl/issues/100

**Comment by oxinabox** [comment]
I attempted to make this change in julia and got good reasons why we shouldn't.

At some point i would like to overhall download in julia, but until then. this can be closed?
https://github.com/JuliaLang/julia/pull/33088

**Comment by rofinn** [comment]
Okay, thanks. I'll add that link to the code and then close.
