### ISSUE TITLE
Add trait for mmap-able?

### ISSUE THREAD

**Issue by oxinabox** [rofinn/FilePathsBase.jl#51]
c.f. https://github.com/JuliaData/CSV.jl/pull/511/files#r332346349

> Note that some FilePaths can be `mmap`s directly, in particular `SystemPath`s
other cannot, like `AWS3.S3Path`s
> But I guess that can be fairly easily handled by treating `SystemPath`s like strings,
and all other `AbstractPaths` like `Cmd`s etc.

This would be a nice usecase for https://github.com/JuliaLang/julia/pull/32732
when I eventually make that work,
since then can just compile-time know if something overload's `hasmethod(MMap.mmap, ...)`

OTOH, I suspect that only SystemPath's are ever going to be mmap-able.
So maybe htis don't need to be extensable,
and existing differentiation between SystemPaths and all other paths is enough.
If so, we can close this

**Comment by rofinn** [comment]
Hmmm, looks like this may be a requirement to have filepaths work with JLD2.jl? I think it might make sense to have a fallback for non-system paths where we download non-system paths locally and then call `MMap.map`?

**Comment by rofinn** [comment]
For now I think we’re just going to support mmap for SystemPaths. If folks want to consistently mmap files then they can cp the file to a temp directory and mmap that.
