### ISSUE TITLE
Current filename implementation seems not ideal

### ISSUE THREAD

**Issue by davidanthoff** [rofinn/FilePathsBase.jl#56]
This
```
julia> filename(p"node-v12.13.1-linux-ppc64le.tar.xz")
"node-v12"
```
does not strike me as a good answer...

I think my gut reaction here would be to _only_ treat the last `.` as separating the filename from the extension.

**Comment by davidanthoff** [comment]
Another point:
```
julia> filename(p"/dist/v12.13.1/node-v12.13.1-linux-ppc64le.tar.xz")
"node-v12"
```
That just strikes me as wrong. The filename here is clearly `node-v12.13.1-linux-ppc64le.tar.xz`... I guess in general in my mind a filename includes the extension...

So I think I have two issues with the current `filename` implementation:
1. It shouldn't split the extension at all
2. I think we need a function that gives us the non-extension part of a filename. I don't know a good name for it :) But it shouldn't stop at the first `.`, IMO.

**Comment by rofinn** [comment]
🤷‍♂ This make me think that we should just drop that method and expect people to use `first(splitext(basename(fp)))`.

**Comment by davidanthoff** [comment]
Yes, I thought a bit more about this, and also ended up thinking that `filename` shouldn't exist :) Just too ambiguous.

We could add `stripext`. It would return `p"foo"` for `p"foo.bar"` and `p"folder/foo"` for `p"folder/foo.bar"`.

**Comment by davidanthoff** [comment]
Ah, wait, but I still think that something like `stripext` should only remove the _last_ extension part. That is certainly the semantics in Windows.
