### ISSUE TITLE
More general `Base.copy` for AbstractPath

### ISSUE THREAD

**Issue by nicoleepp** [rofinn/FilePathsBase.jl#6]
It would be useful to define a more general `copy` that just uses `read` and `write` on AbstractPaths to make extensions easier.

**Comment by rofinn** [comment]
There will be more general versions of `cp` and `mv` in the next release. Please re-open if that isn't what you had in mind. https://github.com/rofinn/FilePathsBase.jl/blob/master/src/path.jl#L479
