### ISSUE TITLE
Use `Vector{String}` for parts

### ISSUE THREAD

**Issue by omus** [rofinn/FilePathsBase.jl#7]
Is there a reason that `Tuple`s are used instead of a `Vector{String}` for the parts field of `WindowsPath` and `POSIXPath`?

https://github.com/rofinn/FilePathsBase.jl/blob/89cd2f13868f331ca8a7c82cf6286e4d3d183852/src/windows.jl#L2

https://github.com/rofinn/FilePathsBase.jl/blob/89cd2f13868f331ca8a7c82cf6286e4d3d183852/src/posix.jl#L2

**Comment by rofinn** [comment]
1. I believe tuples were more performant at the time.
2. I wanted paths to be immutable

**Comment by omus** [comment]
Would probably be best to make these both `Tuple{Vararg{String}}` then
