### ISSUE TITLE
Detect if a file is hidden or not

### ISSUE THREAD

**Issue by yakir12** [rofinn/FilePathsBase.jl#93]
Would be cool to be able to detect that. In unix it's very straight forward. In Windows it's more involved. @oxinabox found these (from slack):
> Apparently the way to do it is to call into the win32 API,
> and use GetFileAttributes (https://docs.microsoft.com/en-gb/windows/win32/api/fileapi/nf-fileapi-getfileattributesa?redirectedfrom=MSDN)then check the flag (i guess via &
 masking) for 0x02
(https://docs.microsoft.com/en-gb/windows/win32/fileio/file-attribute-constants)

**Comment by rofinn** [comment]
How would you want that to work with the API though? Do you just want an `ishidden` function?

**Comment by yakir12** [comment]
Yea, but I was talk out of it cause it seems it's more of a UI of the window manager thing than an actual property of the file. So feel free to do what you will with this feature request.

**Comment by rofinn** [comment]
Alright, I think I agree that this is mostly a UI issue. I suppose we could open a separate issue for adding more windows support.
